provider: eks

cronjob:
  schedule: "0 0 1 * *"
  command: []

image:
  repository: aquasec/kube-bench
  tag: v0.6.9
  pullPolicy: IfNotPresent

extraEnv: []

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
concurrencyPolicy: Forbid
