name: Push Chart
on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
jobs:
  push:
    name: Push to S3 repository
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: apt-get update && apt install -y git curl
      - name: Install Helm
        run: curl -sL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash -s
      - name: Install Helm S3 plugin
        run: helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.14.0
      - name: Adding repository
        env:
          AWS_S3_REPOSITORY: ${{ secrets.AWS_S3_REPOSITORY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: helm repo add lemontech $AWS_S3_REPOSITORY
      - name: Package charts
        run: |
          for chart in charts/*;
            do helm dependencies update $chart && \
            helm package $chart -d ./packages/;
          done
      - name: Push charts to repository
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          for package in packages/*;
            do helm s3 push --ignore-if-exists --relative $package lemontech;
          done;
